sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678



  redis:
    host: localhost
    port: 6379
    password: 12345678
    database: 10



  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tSr7cbR9rHqxC6NLHmG
    access-key-secret: oaVQ9tk2ArN7Tvnc9XfTX8NYb7kFpi
    bucket-name: sky-take-out-chengdu

  wechat:
    appid: wxdbce82982b56ec00
    secret: 10e77dc78940dc8b397b3c4e142e6b5c