sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678



  redis:
    host: localhost
    port: 6379
    password: 12345678
    database: 10



  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    bucket-name: sky-itcast

  wechat:
    appid: wxdbce82982b56ec00
    secret: 10e77dc78940dc8b397b3c4e142e6b5c